import { Router, Request, Response, NextFunction } from 'express';
import { createHash, randomBytes, randomInt, scrypt as sc, timingSafeEqual } from 'node:crypto';
import { promisify } from 'node:util';
import nodemailer from 'nodemailer';
import rateLimit from 'express-rate-limit';
import { checkOtp, createSession, createUser, deleteSession, getSessionUser, getUserByLogin, saveOtp, markEmailVerified, recordLastLogin, pool } from './database/db.js';
import { classifyLoginIdentifier, normalizeEmail, normalizePhilippineMobileNumber } from './identity.js';
const r=Router(), scrypt=promisify(sc), name='bjmp_session';
if (process.env.NODE_ENV==='production' && !process.env.SESSION_SECRET) throw new Error('SESSION_SECRET is required in production.');
const secret=process.env.SESSION_SECRET || randomBytes(32).toString('hex');
const sum=(x:string)=>createHash('sha256').update(secret+':'+x).digest('hex');
const loginLim=rateLimit({windowMs:900000,limit:10,standardHeaders:true,legacyHeaders:false,message:{error:'Too many sign-in attempts. Please try again later.'}});
const registerLim=rateLimit({windowMs:900000,limit:10,standardHeaders:true,legacyHeaders:false,message:{error:'Too many registration attempts. Please try again later.'}});
const verifyLim=rateLimit({windowMs:900000,limit:10,standardHeaders:true,legacyHeaders:false,message:{error:'Too many verification attempts. Please try again later.'}});
const resendLim=rateLimit({windowMs:900000,limit:3,standardHeaders:true,legacyHeaders:false,message:{error:'Too many verification requests. Please try again later.'}});
async function authAudit(q:Request,user:any,action:string,result:string){await pool.query('INSERT INTO audit_logs(actor_user_id,actor_role,action,target_type,target_id,result,details,ip_address) VALUES(?,?,?,?,?,?,?,?)',[user?.id||null,user?.role||'ANONYMOUS',action,'AUTH',user?.id?String(user.id):null,result,JSON.stringify({}),q.ip||null])}
function token(q:Request){return(q.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='))?.slice(name.length+1)}
function clear(s:Response){s.setHeader('Set-Cookie',name+'=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'+(process.env.NODE_ENV==='production'?'; Secure':''))}
async function issue(u:any,s:Response){const t=randomBytes(32).toString('hex');await createSession(sum(t),u.id,new Date(Date.now()+Number(process.env.SESSION_TTL_HOURS||12)*3600000));s.setHeader('Set-Cookie',name+'='+t+'; HttpOnly; SameSite=Lax; Path=/; Max-Age='+(Number(process.env.SESSION_TTL_HOURS||12)*3600)+(process.env.NODE_ENV==='production'?'; Secure':''))}
export async function resolveSocketSession(cookieHeader:string|undefined){const raw=(cookieHeader||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='))?.slice(name.length+1);if(!raw)return null;const user=await getSessionUser(sum(raw));return user?{id:String(user.id),role:user.role}:null}
export async function auth(q:Request,s:Response,n:NextFunction){try{const t=token(q);if(!t)return s.status(401).json({error:'Please sign in to continue.'});const u=await getSessionUser(sum(t));if(!u){clear(s);return s.status(401).json({error:'Session expired. Please sign in again.'})}(q as any).user=u;n()}catch{s.status(500).json({error:'Session validation failed.'})}}
export function admin(q:Request,s:Response,n:NextFunction){if(!['ADMIN','SUPER_ADMIN'].includes((q as any).user?.role))return s.status(403).json({error:'You do not have permission.'});n()}
export function kycReviewer(q:Request,s:Response,n:NextFunction){if(!['ADMIN','SUPER_ADMIN','VERIFICATION_OFFICER'].includes((q as any).user?.role))return s.status(403).json({error:'You do not have permission.'});n()}
export function worker(q:Request,s:Response,n:NextFunction){if(!['ADMIN','WORKER','GUARD'].includes((q as any).user?.role))return s.status(403).json({error:'You do not have permission.'});n()}
export function visitorActive(q:Request,s:Response,n:NextFunction){const u=(q as any).user;if(u?.role!=='VISITOR')return s.status(403).json({error:'You do not have permission.'});if(!['ACTIVE','ACTIVATED'].includes(u.accountStatus))return s.status(403).json({error:'Complete account and identity verification before continuing.'});n()}
export async function hashPass(p:string){const salt=randomBytes(16),key=await scrypt(p,salt,64) as Buffer;return 'scrypt:'+salt.toString('hex')+':'+key.toString('hex')}
async function verify(p:string,v:string){const[,sa,ke]=v.split(':');if(!sa||!ke)return false;const a=Buffer.from(ke,'hex'),b=await scrypt(p,Buffer.from(sa,'hex'),a.length) as Buffer;return a.length===b.length&&timingSafeEqual(a,b)}
async function sendCode(dest:{email?:string|null;phone?:string|null},code:string){
 if(dest.email){if(!process.env.SMTP_HOST||!process.env.SMTP_USER||!process.env.SMTP_PASS)throw Error('Email verification is not configured.');const m=nodemailer.createTransport({host:process.env.SMTP_HOST,port:+(process.env.SMTP_PORT||587),secure:process.env.SMTP_SECURE==='true',auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}});await m.sendMail({from:process.env.SMTP_FROM||process.env.SMTP_USER,to:dest.email,subject:'Account verification code',text:'Code: '+code+' (expires in 10 minutes)'});return false}
 if(process.env.SMS_PROVIDER==='mock'&&process.env.NODE_ENV!=='production')return true;
 if(process.env.SMS_PROVIDER==='twilio'&&process.env.SMS_API_URL&&process.env.SMS_ACCOUNT_ID&&process.env.SMS_AUTH_TOKEN&&process.env.SMS_FROM){const url=process.env.SMS_API_URL.replace('{accountId}',process.env.SMS_ACCOUNT_ID),body=new URLSearchParams({To:dest.phone!,From:process.env.SMS_FROM,Body:'Verification code: '+code}),authorization=Buffer.from(process.env.SMS_ACCOUNT_ID+':'+process.env.SMS_AUTH_TOKEN).toString('base64'),x=await fetch(url,{method:'POST',headers:{Authorization:'Basic '+authorization,'Content-Type':'application/x-www-form-urlencoded'},body});if(x.ok)return false}
 throw Error('SMS verification is not configured.');
}
async function issueCode(u:any,res:Response){const code=String(randomInt(100000,1000000));await saveOtp(u.id,'VERIFY',sum(code),new Date(Date.now()+600000));const mock=await sendCode({email:u.email||null,phone:u.mobileNumber||null},code);return mock&&process.env.NODE_ENV!=='production'?code:undefined}
r.post('/login',loginLim,async(q,s)=>{try{const id=String(q.body.identifier||q.body.email||q.body.mobileNumber||'').trim(),p=String(q.body.password||''),parsed=classifyLoginIdentifier(id);if(!parsed||!p)return s.status(400).json({error:'Enter a valid email address or Philippine mobile number, and password.'});const u=await getUserByLogin(parsed.value,parsed.type);if(!u||!u.passwordHash.startsWith('scrypt:')||!await verify(p,u.passwordHash)||['SUSPENDED','REJECTED'].includes(u.accountStatus)){await authAudit(q,null,'FAILED_LOGIN','FAILURE');return s.status(401).json({error:'Invalid email/mobile number or password.'});}await recordLastLogin(u.id);await authAudit(q,u,'LOGIN','SUCCESS');await issue(u,s);const{passwordHash,...user}=u;s.json({success:true,user})}catch{s.status(500).json({error:'Sign in failed.'})}});
r.post('/register',registerLim,async(q,s)=>{let u:any;try{const email=normalizeEmail(q.body.email||''),phone=normalizePhilippineMobileNumber(q.body.mobileNumber||'');const suppliedEmail=String(q.body.email||'').trim();const suppliedPhone=String(q.body.mobileNumber||'').trim();const p=String(q.body.password||'');if(suppliedEmail&&!email)return s.status(400).json({error:'Please enter a valid email address.'});if(suppliedPhone&&!phone)return s.status(400).json({error:'Please enter a valid Philippine mobile number.'});if(!email&&!phone)return s.status(400).json({error:'Enter an email address or Philippine mobile number.'});if(email&&phone)return s.status(400).json({error:'Choose one contact method: email or Philippine mobile number.'});if(!/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z0-9]).{8,128}$/.test(p))return s.status(400).json({error:'Password needs 8+ characters, uppercase, lowercase, number, and symbol.'});if(await getUserByLogin(email||phone!,email?'email':'phone'))return s.status(409).json({error:'This email or mobile number is already registered.'});u=await createUser({...q.body,role:'VISITOR',email,mobileNumber:phone,passwordHash:await hashPass(p),accountStatus:'PENDING_VERIFICATION',validIdType:null,validIdPhotoUrl:null,facePhotoUrl:null});const devCode=await issueCode(u,s);await issue(u,s);const{passwordHash,...user}=u;s.status(201).json({success:true,user,...(devCode?{developmentOtp:devCode}:{})})}catch(e:any){if(e?.code==='ER_DUP_ENTRY')return s.status(409).json({error:'This email or mobile number is already registered.'});s.status(u?503:400).json({error:u?'Account created but verification could not be completed. Please try resending the code.':'Registration failed. Check your details.'})}});
r.post('/resend-otp',resendLim,auth,async(q,s)=>{try{const user=(q as any).user;if(user.emailVerified||user.phoneVerified)return s.status(409).json({error:'This contact is already verified.'});const developmentOtp=await issueCode(user,s);s.json({success:true,...(developmentOtp?{developmentOtp}:{})})}catch{s.status(503).json({error:'Verification delivery is unavailable. Please try again later.'})}});
r.post('/verify-otp',verifyLim,auth,async(q,s)=>{try{const user=(q as any).user,x=await checkOtp(user.id,'VERIFY',sum(String(q.body.code||'')));if(x!=='OK')return s.status(x==='LOCKED'?429:400).json({error:x==='EXPIRED'?'Code expired.':x==='LOCKED'?'Too many attempts.':'Invalid code.'});const updated=await markEmailVerified(user.id);s.json({success:true,user:updated})}catch{s.status(500).json({error:'Verification failed.'})}});
r.post('/logout',auth,async(q,s)=>{const t=token(q),u=(q as any).user;if(t)await deleteSession(sum(t));await authAudit(q,u,'LOGOUT','SUCCESS');clear(s);s.json({success:true})});r.get('/me',auth,(q,s)=>s.json({user:(q as any).user}));export default r;
