import React,{useEffect,useState} from 'react';
import { CalendarDays, Clock3, Users, ScanLine, Search, RotateCw, ShieldCheck, AlertTriangle, Fingerprint, ArrowRight } from 'lucide-react';
import { api } from '../../services/api';
import { UserProfile } from '../../types';

type Visit=any;
export const WorkerDashboard:React.FC<{user:UserProfile}>=({user})=>{
 const [history,setHistory]=useState<any[]>([]),[visits,setVisits]=useState<Visit[]>([]),[selected,setSelected]=useState<Visit|null>(null),[code,setCode]=useState(''),[search,setSearch]=useState(''),[results,setResults]=useState<Visit[]>([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const refresh=()=>Promise.all([api.getWorkerVisits(),api.getWorkerHistory()]).then(([v,h])=>{setVisits(v);setHistory(h)}).catch(e=>setError(e.message));useEffect(()=>{void refresh()},[]);
 const scan=async(e:React.FormEvent)=>{e.preventDefault();setError('');setMessage('');setSelected(null);setBusy(true);try{const r=await api.workerScan(code);setSelected({...r.result,canProceed:r.canProceed});setMessage(r.canProceed?'Appointment and account checks passed.':'This visit does not meet the arrival checks.');}catch(e){setError(e instanceof Error?e.message:'Could not match the pass.')}finally{setBusy(false)}};
 const find=async(e:React.FormEvent)=>{e.preventDefault();setError('');setBusy(true);try{setResults(await api.workerSearchVisitors(search))}catch(e){setError(e instanceof Error?e.message:'Search failed.')}finally{setBusy(false)}};
 const process=async()=>{if(!selected)return;setBusy(true);try{const r=await api.workerVerifyVisit(String(selected.id),'FAILED');setMessage(r.message);setSelected(null)}catch(e){setError(e instanceof Error?e.message:'Verification unavailable.')}finally{setBusy(false)}};
 const card='rounded-2xl border border-white/10 bg-slate-950/75 p-5 shadow-lg';
 return <main className="mx-auto max-w-7xl px-4 py-7 text-slate-100 sm:px-6"><header className="mb-7 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-300">Visitation operations</p><h1 className="mt-1 text-3xl font-extrabold">Worker Desk</h1><p className="mt-1 text-sm text-slate-300">Welcome, {user.firstName}. Process today's approved visits.</p></div><button onClick={refresh} className="flex items-center gap-2 rounded-lg border border-white/15 px-3 py-2 text-sm hover:bg-white/10"><RotateCw className="h-4 w-4"/>Refresh</button></header>
 <section className="mb-6 grid gap-4 sm:grid-cols-3"><div className={card}><CalendarDays className="mb-3 h-5 w-5 text-blue-300"/><p className="text-xs text-slate-400">Today's scheduled visits</p><p className="mt-1 text-3xl font-black">{visits.length}</p></div><div className={card}><Clock3 className="mb-3 h-5 w-5 text-amber-300"/><p className="text-xs text-slate-400">Approved for processing</p><p className="mt-1 text-3xl font-black">{visits.filter(x=>x.visit.status==='Approved').length}</p></div><div className={card}><Users className="mb-3 h-5 w-5 text-emerald-300"/><p className="text-xs text-slate-400">Waiting for arrival check</p><p className="mt-1 text-3xl font-black">{visits.filter(x=>x.visit.status==='Approved').length}</p></div></section>
 <section className="grid gap-5 lg:grid-cols-[1.05fr_.95fr]"><div className={`${card} space-y-5`}><div><h2 className="flex items-center gap-2 text-lg font-bold"><ScanLine className="h-5 w-5 text-blue-300"/>Process visitor pass</h2><p className="mt-1 text-xs text-slate-400">Scan QR or enter the visit reference number.</p></div><form onSubmit={scan} className="flex gap-2"><input value={code} onChange={e=>setCode(e.target.value)} className="min-w-0 flex-1 rounded-lg border border-white/15 bg-slate-900 px-3 py-3 text-sm" placeholder="Visit reference / QR value"/><button disabled={busy||!code.trim()} className="rounded-lg bg-blue-500 px-4 font-bold text-slate-950 disabled:opacity-50">Find</button></form>
 {selected&&<div className="rounded-xl border border-blue-300/20 bg-blue-300/5 p-4"><div className="flex items-center justify-between"><h3 className="font-bold">Visitor and visit</h3><span className="rounded-full bg-blue-400/10 px-2.5 py-1 text-xs text-blue-200">{selected.visit.status}</span></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><div><p className="text-[10px] uppercase tracking-wider text-slate-400">Visitor</p><p className="mt-1 font-semibold">{selected.visitor.name}</p><p className="text-xs text-slate-400">{selected.visitor.visitorId} · {selected.visitor.mobileMasked||'Contact hidden'}</p><p className="mt-2 text-xs">Account: <span className="text-slate-300">{selected.visitor.accountStatus}</span></p><p className="text-xs">ID review: <span className="text-slate-300">{selected.visitor.verificationStatus}</span></p></div><div className="rounded-lg border border-white/10 bg-slate-950/60 p-3"><p className="text-[10px] uppercase tracking-wider text-blue-300">Visiting PDL</p><p className="mt-1 font-semibold">{selected.pdl.name}</p><p className="text-xs text-slate-400">{selected.pdl.pdlId}</p><p className="mt-3 text-xs"><CalendarDays className="mr-1 inline h-3 w-3"/>{selected.visit.scheduledDate}</p><p className="text-xs"><Clock3 className="mr-1 inline h-3 w-3"/>{selected.visit.scheduledTime}</p><p className="mt-2 text-xs text-slate-300">{selected.appointmentReference} · {selected.visit.relationship}</p></div></div><div className="mt-4 flex gap-2 rounded-lg bg-slate-950/70 p-3 text-xs text-slate-300"><Fingerprint className="h-4 w-4 shrink-0 text-amber-300"/><span>Fingerprint device is not connected. Do not admit a visitor based on QR matching alone; refer to the records desk.</span></div><button onClick={process} disabled={busy||!selected.canProceed} className="mt-4 flex w-full items-center justify-center gap-2 rounded-lg border border-amber-300/20 bg-amber-300/10 p-3 text-sm font-semibold text-amber-100 disabled:opacity-50">Record that fingerprint verification is unavailable <ArrowRight className="h-4 w-4"/></button></div>}
 {message&&<p className="text-sm text-slate-300">{message}</p>}{error&&<p className="flex items-center gap-2 text-sm text-rose-300"><AlertTriangle className="h-4 w-4"/>{error}</p>}</div>
 <div className={`${card} space-y-4`}><div><h2 className="text-lg font-bold">Search upcoming visitors</h2><p className="mt-1 text-xs text-slate-400">Only approved visit details needed for processing are shown.</p></div><form onSubmit={find} className="flex gap-2"><input value={search} onChange={e=>setSearch(e.target.value)} className="min-w-0 flex-1 rounded-lg border border-white/15 bg-slate-900 px-3 py-2.5 text-sm" placeholder="Visitor or pass reference"/><button className="rounded-lg border border-white/15 px-3"><Search className="h-4 w-4"/></button></form><div className="max-h-[430px] space-y-2 overflow-auto">{(results.length?results:visits).map((v:Visit)=><button key={v.id} onClick={()=>{setSelected(v);setMessage('');setError('')}} className="w-full rounded-xl border border-white/10 bg-slate-900/70 p-3 text-left hover:border-blue-300/40"><div className="flex justify-between gap-2"><span className="font-semibold">{v.visitor.name}</span><span className="text-[10px] text-slate-400">{v.visit.scheduledDate}</span></div><p className="mt-1 text-xs text-slate-300">Visiting {v.pdl.name} <span className="text-slate-500">({v.pdl.pdlId})</span></p><p className="mt-1 text-[10px] text-slate-400">{v.appointmentReference} · {v.visit.scheduledTime}</p></button>)}{!results.length&&!visits.length&&<p className="py-8 text-center text-sm text-slate-500">No visits found.</p>}</div><div className="border-t border-white/10 pt-3"><h3 className="mb-2 text-sm font-semibold">My recent processing activity</h3><div className="space-y-1">{history.slice(0,4).map(x=><p key={x.id} className="text-[10px] text-slate-400">{new Date(x.created_at).toLocaleString()} · {x.action} · {x.result}</p>)}{!history.length&&<p className="text-[10px] text-slate-500">No processing actions recorded.</p>}</div></div></div></section>
 <div className="mt-5 flex items-center gap-2 text-xs text-slate-400"><ShieldCheck className="h-4 w-4 text-blue-300"/>Worker view only displays visitation details and masked contact information.</div></main>
};
