import React,{useEffect,useState} from 'react';
import { ShieldCheck, Upload, FileImage, AlertCircle, CheckCircle2, Clock, RefreshCw } from 'lucide-react';
import { UserProfile } from '../../types';
import { api } from '../../services/api';
import { VALID_ID_OPTIONS } from '../../data/bjmpData';

const toDataUrl=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('Could not read the image.'));reader.readAsDataURL(file)});
const acceptedIds=VALID_ID_OPTIONS;
export const IdentityVerificationPage:React.FC<{user:UserProfile;onLogout:()=>void}>=({user,onLogout})=>{
 const [status,setStatus]=useState<any>({status:'NOT_SUBMITTED'}),[idType,setIdType]=useState(acceptedIds[0]),[idNumber,setIdNumber]=useState(''),[fullName,setFullName]=useState(`${user.firstName} ${user.middleName||''} ${user.lastName} ${user.suffix||''}`.replace(/\s+/g,' ').trim()),[front,setFront]=useState<File|null>(null),[back,setBack]=useState<File|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[success,setSuccess]=useState(false);
 const load=()=>api.getKycStatus().then(x=>setStatus(x.status)).catch(()=>setStatus({status:'NOT_SUBMITTED'}));useEffect(()=>{void load()},[]);
 const choose=(file:File|null,setter:(f:File|null)=>void)=>{setError('');if(!file){setter(null);return}if(!['image/jpeg','image/png'].includes(file.type)){setError('Upload a JPG or PNG image.');return}if(file.size<2048||file.size>5*1024*1024){setError('Each image must be between 2 KB and 5 MB.');return}setter(file)};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(!idNumber.trim()||!fullName.trim()){setError('Enter the name and ID number shown on your ID.');return}if(!front){setError('Upload a clear photo of the front of your ID.');return}setBusy(true);try{const [frontImage,backImage]=await Promise.all([toDataUrl(front),back?toDataUrl(back):Promise.resolve(undefined)]);const result=await api.submitKyc({idType,idNumber,fullName,dateOfBirth:user.dateOfBirth||undefined,address:[user.address?.houseUnitStreet,user.address?.municipality].filter(Boolean).join(', '),frontImage,backImage});setStatus({status:result.status,automated_check:result.automatedCheck,submitted_at:new Date().toISOString()});setSuccess(true);setIdNumber('');setFront(null);setBack(null)}catch(e){setError(e instanceof Error?e.message:'Could not submit your documents.')}finally{setBusy(false)}};
 const labels:Record<string,string>={NOT_SUBMITTED:'Not submitted',PENDING_REVIEW:'Pending administrator review',PROCESSING:'Processing',VERIFIED:'Identity review approved',REJECTED:'Rejected',NEEDS_RESUBMISSION:'Resubmission required'};
 return <main className="mx-auto max-w-4xl px-4 py-10 text-slate-100 sm:px-6"><section className="overflow-hidden rounded-2xl border border-white/15 bg-slate-950/85 shadow-2xl"><header className="border-b border-white/10 bg-blue-950/40 p-6 sm:p-8"><div className="flex items-center gap-3"><div className="rounded-xl bg-blue-500/15 p-3 text-blue-300"><ShieldCheck className="h-6 w-6"/></div><div><p className="text-xs font-bold uppercase tracking-widest text-blue-300">Account step 2</p><h1 className="text-2xl font-bold">Identity Verification</h1></div></div><p className="mt-4 max-w-2xl text-sm leading-6 text-slate-300">To protect users and support secure registration, submit a photo ID for document checks and administrator review. Automated checks do not officially verify a government-issued ID.</p></header>
 <div className="p-6 sm:p-8">{error&&<div className="mb-5 flex gap-2 rounded-xl border border-rose-300/30 bg-rose-300/10 p-3 text-sm text-rose-100"><AlertCircle className="h-4 w-4 shrink-0"/>{error}</div>}
 <div className="mb-6 flex items-start gap-3 rounded-xl border border-white/10 bg-white/5 p-4"><div className="mt-0.5 text-blue-300">{status.status==='VERIFIED'?<CheckCircle2/>:<Clock/>}</div><div><p className="font-semibold">{labels[status.status]||status.status}</p><p className="mt-1 text-xs text-slate-400">{status.submitted_at?`Submitted ${new Date(status.submitted_at).toLocaleString()}`:'Complete this step before requesting visitation.'}</p>{status.rejection_reason&&<p className="mt-2 text-sm text-amber-200">Administrator note: {status.rejection_reason}</p>}</div></div>
 {['PENDING_REVIEW','PROCESSING','VERIFIED'].includes(status.status)?<p className="rounded-xl bg-slate-900/80 p-5 text-sm leading-6 text-slate-300">{status.status==='VERIFIED'?'Your document review is approved. The facility will complete any remaining in-person biometric step before full visitation access.':'Your documents are stored privately and awaiting administrator review. We will show the result here.'}</p>:<form onSubmit={submit} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm text-slate-300">ID type<select className="mt-1 w-full rounded-lg border border-white/15 bg-slate-900 p-3 text-white" value={idType} onChange={e=>setIdType(e.target.value)}>{acceptedIds.map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm text-slate-300">ID number<input className="mt-1 w-full rounded-lg border border-white/15 bg-slate-900 p-3 text-white" value={idNumber} onChange={e=>setIdNumber(e.target.value)} maxLength={80} autoComplete="off" required/></label><label className="text-sm text-slate-300 sm:col-span-2">Full name as shown on ID<input className="mt-1 w-full rounded-lg border border-white/15 bg-slate-900 p-3 text-white" value={fullName} onChange={e=>setFullName(e.target.value)} required/></label></div>
 <div className="grid gap-4 sm:grid-cols-2">{[['front','Upload ID front',front,setFront],['back','Upload ID back (if required)',back,setBack]].map(([key,label,file,setter]:any)=><label key={key} className="cursor-pointer rounded-xl border border-dashed border-white/20 bg-slate-900/70 p-5 text-center hover:border-blue-400"><input type="file" className="sr-only" accept="image/jpeg,image/png" onChange={e=>choose(e.target.files?.[0]||null,setter)}/><FileImage className="mx-auto mb-2 h-7 w-7 text-blue-300"/><span className="block text-sm font-semibold text-white">{label}</span><span className="mt-1 block text-xs text-slate-400">{file?file.name:'JPG or PNG, 2 KB–5 MB'}</span><Upload className="mx-auto mt-3 h-4 w-4 text-slate-400"/></label>)}</div>
 <p className="text-xs leading-5 text-slate-400">Automated checks validate file format, dimensions, and compare the submitted name with your account. OCR and official ID verification are not connected. An administrator must review your submission.</p><button disabled={busy} className="w-full rounded-xl bg-blue-500 px-5 py-3 font-bold text-slate-950 disabled:opacity-50">{busy?'Submitting securely…':status.status==='NEEDS_RESUBMISSION'||status.status==='REJECTED'?'Submit corrected documents':'Submit for verification'}</button></form>}
 <div className="mt-6 flex justify-end border-t border-white/10 pt-4"><button onClick={onLogout} className="text-sm text-slate-400 hover:text-white">Sign out</button></div>{success&&<div className="fixed bottom-5 right-5 flex items-center gap-2 rounded-xl border border-emerald-400/30 bg-slate-900 p-4 text-sm text-emerald-100"><CheckCircle2 className="h-4 w-4"/>Documents sent for review.</div>}</div></section></main>
};
