import React,{useEffect,useState} from 'react';
import { Eye, ShieldCheck, FileCheck2, Search, Check, X, RefreshCw, AlertTriangle } from 'lucide-react';
import { api } from '../../services/api';

export const AdminKycPanel:React.FC<{initialStatus?:string;onReviewed?:()=>Promise<void>|void}>=({initialStatus='',onReviewed})=>{
 const [filter,setFilter]=useState(initialStatus),[rows,setRows]=useState<any[]>([]),[selected,setSelected]=useState<any|null>(null),[images,setImages]=useState<Record<string,string>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState('');
 const load=()=>api.getAdminKyc(filter||undefined).then(setRows).catch(e=>setError(e.message));useEffect(()=>{void load()},[filter]);
 const open=async(id:string)=>{setError('');setSelected(null);setBusy(true);try{const d=await api.adminKycDetail(id);setSelected(d.submission);const loaded:Record<string,string>={};for(const doc of d.submission.documents){try{loaded[doc.side]=await api.getKycDocument(doc.url)}catch{}}setImages(loaded)}catch(e){setError(e instanceof Error?e.message:'Could not load submission.')}finally{setBusy(false)}};
 useEffect(()=>()=>Object.values(images).forEach(URL.revokeObjectURL),[images]);
 const review=async(status:'VERIFIED'|'REJECTED'|'NEEDS_RESUBMISSION')=>{if(!selected)return;let reason='';if(status!=='VERIFIED'){const response=window.prompt(status==='REJECTED'?'Reason for rejection (required):':'What needs to be corrected?');if(response===null)return;reason=response.trim();if(!reason){setError('Provide a review reason.');return}}if(status==='VERIFIED'&&!window.confirm('Approve this document review? Account access remains pending in-person biometric verification.'))return;setBusy(true);setError('');try{await api.reviewKyc(String(selected.id),status,reason);setSelected(null);setImages({});await load();await onReviewed?.()}catch(e){setError(e instanceof Error?e.message:'Could not save review.')}finally{setBusy(false)}};
 const filtered=rows.filter(x=>`${x.first_name} ${x.last_name} ${x.id_type} ${x.id}`.toLowerCase().includes(query.toLowerCase()));
 const cls='rounded-lg border border-white/10 bg-slate-900/70';
 return <section className="rounded-2xl border border-white/10 bg-slate-950/75 p-5 text-slate-100 sm:p-6"><header className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-300">Identity review</p><h2 className="text-2xl font-bold">Document Verification</h2><p className="mt-1 text-xs text-slate-400">Uploaded IDs require administrator review. Automated checks do not establish official government verification.</p></div><button onClick={load} className="rounded-lg border border-white/15 p-2 hover:bg-white/10" aria-label="Refresh"><RefreshCw className="h-4 w-4"/></button></header>
 {error&&<p className="mb-4 flex gap-2 rounded-lg border border-rose-300/20 bg-rose-300/10 p-3 text-sm text-rose-200"><AlertTriangle className="h-4 w-4 shrink-0"/>{error}</p>}
 <div className="mb-4 flex flex-wrap gap-2"><label className="relative min-w-[220px] flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-500"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name or ID type" className="w-full rounded-lg border border-white/10 bg-slate-900 py-2.5 pl-9 pr-3 text-sm"/></label><select className="rounded-lg border border-white/10 bg-slate-900 px-3 text-sm" value={filter} onChange={e=>setFilter(e.target.value)}>{['','PENDING_REVIEW','PROCESSING','VERIFIED','REJECTED','NEEDS_RESUBMISSION'].map(x=><option key={x} value={x}>{x||'All statuses'}</option>)}</select></div>
 <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="text-[10px] uppercase tracking-wider text-slate-400"><tr><th className="p-3">Applicant</th><th className="p-3">ID type</th><th className="p-3">Submitted</th><th className="p-3">Status / check</th><th className="p-3">Reviewer</th><th className="p-3">Action</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id} className="border-t border-white/5"><td className="p-3 font-semibold">{x.first_name} {x.last_name}</td><td className="p-3 text-slate-300">{x.id_type}</td><td className="p-3 text-xs text-slate-400">{new Date(x.submitted_at).toLocaleString()}</td><td className="p-3"><span className="rounded-full bg-blue-400/10 px-2 py-1 text-[10px] text-blue-200">{x.status}</span><div className="mt-1 text-[10px] text-slate-500">{x.automated_check?.overall||'ADMIN_REVIEW_REQUIRED'}</div></td><td className="p-3 text-xs text-slate-400">{x.reviewer_name||'—'}</td><td className="p-3"><button onClick={()=>open(String(x.id))} className="inline-flex items-center gap-1 rounded-lg border border-white/10 px-2.5 py-1.5 text-xs hover:border-blue-300/30"><Eye className="h-3.5 w-3.5"/>View</button></td></tr>)}</tbody></table>{!filtered.length&&<div className="p-10 text-center text-sm text-slate-500"><FileCheck2 className="mx-auto mb-2 h-7 w-7"/>No submissions match this filter.</div>}</div>
 {selected&&<div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/80 p-4"><div className="max-h-[90vh] w-full max-w-5xl overflow-y-auto rounded-2xl border border-white/15 bg-slate-950 p-5 sm:p-7"><header className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-widest text-blue-300">Submission {selected.id}</p><h3 className="mt-1 text-xl font-bold">Compare submitted details</h3></div><button onClick={()=>{setSelected(null);setImages({})}} className="rounded-lg p-2 text-slate-400 hover:bg-white/10"><X/></button></header><div className="mt-5 grid gap-5 md:grid-cols-2"><div className={`${cls} p-4`}><h4 className="mb-3 font-bold">USER PROVIDED</h4><p className="text-sm">Name: {selected.userProvided.name}</p><p className="mt-1 text-sm">ID type: {selected.userProvided.idType}</p><p className="mt-1 text-sm">ID number: {selected.userProvided.idNumberMasked}</p><p className="mt-1 text-sm">DOB: {selected.userProvided.dateOfBirth||'Not provided'}</p></div><div className={`${cls} p-4`}><h4 className="mb-3 font-bold">AUTOMATED CHECKS</h4><pre className="whitespace-pre-wrap text-xs text-slate-300">{JSON.stringify(selected.automatedCheck,null,2)}</pre><p className="mt-3 text-xs text-amber-200">OCR: unavailable. Official government ID validation: not connected. Administrator review required.</p></div></div><h4 className="mb-3 mt-6 font-bold">Protected document images</h4><div className="grid gap-4 sm:grid-cols-2">{['front','back'].map(side=><div key={side} className={`${cls} p-3`}><p className="mb-2 text-xs uppercase text-slate-400">{side}</p>{images[side]?<img src={images[side]} alt={`Submitted ID ${side}`} className="max-h-72 w-full rounded-lg object-contain"/>:<div className="grid h-36 place-items-center text-sm text-slate-500">No {side} image uploaded.</div>}</div>)}</div><div className="mt-6 flex flex-wrap justify-end gap-2 border-t border-white/10 pt-4"><button disabled={busy} onClick={()=>review('NEEDS_RESUBMISSION')} className="rounded-lg border border-amber-300/25 px-3 py-2 text-xs text-amber-100">Request resubmission</button><button disabled={busy} onClick={()=>review('REJECTED')} className="rounded-lg border border-rose-300/25 px-3 py-2 text-xs text-rose-100">Reject</button><button disabled={busy} onClick={()=>review('VERIFIED')} className="flex items-center gap-2 rounded-lg bg-emerald-400 px-4 py-2 text-xs font-bold text-slate-950"><Check className="h-4 w-4"/>Approve review</button></div></div></div>}
 </section>
};
