import React,{useEffect,useState} from 'react';
import { Archive, RotateCcw, RefreshCw, Clock3, Search, History } from 'lucide-react';
import { api } from '../../services/api';

export const AdminArchivePanel:React.FC=()=>{
 const [rows,setRows]=useState<any[]>([]),[type,setType]=useState(''),[q,setQ]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(''),[selected,setSelected]=useState<any|null>(null),[history,setHistory]=useState<any[]>([]),[record,setRecord]=useState<any|null>(null);
 const load=()=>api.getAdminArchive(type,q).then(setRows).catch(e=>setError(e.message));
 useEffect(()=>{void load()},[type]);
 const restore=async(row:any)=>{if(!window.confirm(`Restore ${row.record_type} ${row.record_label}? This will return the record to active lists.`))return;setBusy(row.record_id);try{await api.restoreArchivedRecord(row.record_type,row.record_id);await load()}catch(e:any){setError(e.message)}finally{setBusy('')}};
 const showHistory=async(row:any)=>{setSelected(row);setRecord(null);try{const [h,d]=await Promise.all([api.getArchiveHistory(row.record_type,row.record_id),api.getArchivedRecord(row.record_type,row.record_id)]);setHistory(h);setRecord(d)}catch(e:any){setError(e.message)}};
 return <section className="rounded-2xl border border-white/10 bg-slate-950/75 p-5 text-slate-100 sm:p-6"><header className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-300">Administrator tools</p><h2 className="text-2xl font-bold">Archive / Recycle Bin</h2><p className="mt-1 text-xs text-slate-400">Archived records remain stored and can be restored. Historical visit records are retained.</p></div><button onClick={load} className="rounded-lg border border-white/15 p-2"><RefreshCw className="h-4 w-4"/></button></header>
 <div className="mb-4 flex flex-wrap gap-2"><label className="relative min-w-48 flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-500"/><input aria-label="Search archive" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void load()} placeholder="Search archive" className="w-full rounded-lg border border-white/10 bg-slate-900 py-2 pl-9 pr-3 text-sm"/></label><select value={type} onChange={e=>setType(e.target.value)} className="rounded-lg border border-white/10 bg-slate-900 px-3 py-2 text-sm"><option value="">All record types</option><option value="USER">Users</option><option value="PDL">PDL records</option><option value="APPOINTMENT">Visits</option><option value="ANNOUNCEMENT">Announcements</option><option value="SECURITY_INCIDENT">Security incidents</option></select><button onClick={load} className="rounded-lg bg-blue-500 px-4 py-2 text-sm font-bold text-slate-950">Search</button></div>
 {error&&<p className="mb-3 text-sm text-rose-300">{error}</p>}<div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left text-sm"><thead className="text-[10px] uppercase text-slate-400"><tr><th className="p-3">Record</th><th className="p-3">Created</th><th className="p-3">Archived</th><th className="p-3">Archived by</th><th className="p-3">Reason / prior status</th><th className="p-3">Actions</th></tr></thead><tbody>{rows.map(row=><tr key={`${row.record_type}-${row.record_id}`} className="border-t border-white/5"><td className="p-3"><span className="text-[10px] text-blue-300">{row.record_type}</span><div className="font-semibold">{row.record_label}</div><div className="text-xs text-slate-500">{row.record_id}</div></td><td className="p-3 text-xs text-slate-400">{row.original_created_at?new Date(row.original_created_at).toLocaleString():'—'}</td><td className="p-3 text-xs text-slate-400">{new Date(row.archived_at).toLocaleString()}</td><td className="p-3 text-xs">{row.archived_by_name||`Admin ${row.archived_by||''}`}</td><td className="max-w-56 p-3 text-xs text-slate-300">{row.archive_reason||'—'}<div className="mt-1 text-slate-500">Previous: {row.previous_status||'—'}</div></td><td className="p-3"><div className="flex gap-2"><button onClick={()=>void showHistory(row)} className="rounded border border-white/10 p-2 text-slate-300" title="View archive history"><History className="h-4 w-4"/></button><button disabled={busy===row.record_id} onClick={()=>void restore(row)} className="flex items-center gap-1 rounded bg-blue-500/15 px-2 py-2 text-xs text-blue-200 disabled:opacity-50"><RotateCcw className="h-3.5 w-3.5"/>Restore</button></div></td></tr>)}</tbody></table>{!rows.length&&<div className="p-10 text-center text-sm text-slate-500"><Archive className="mx-auto mb-2 h-7 w-7"/>No archived records found.</div>}</div>
 {selected&&<div className="fixed inset-0 z-[90] flex items-center justify-center bg-black/70 p-4" onClick={()=>setSelected(null)}><section onClick={e=>e.stopPropagation()} className="w-full max-w-xl rounded-2xl border border-white/10 bg-slate-950 p-5"><header className="mb-4 flex justify-between"><div><p className="text-xs text-blue-300">Original record and archive history</p><h3 className="font-bold">{selected.record_label}</h3></div><button onClick={()=>setSelected(null)} className="text-slate-400">Close</button></header>{record&&<pre className="mb-4 max-h-56 overflow-auto rounded-lg bg-slate-900 p-3 text-xs text-slate-300">{JSON.stringify(record,null,2)}</pre>}{history.map(item=><div key={item.id} className="border-t border-white/10 py-3 text-sm"><div className="flex items-center gap-2 font-semibold"><Clock3 className="h-4 w-4 text-blue-300"/>{item.action} · {new Date(item.performed_at).toLocaleString()}</div><p className="mt-1 text-xs text-slate-400">{item.first_name?`${item.first_name} ${item.last_name}`:'Administrator'} · {item.reason||item.previous_status||'—'}</p></div>)}</section></div>}
 </section>;
};
