import { JailFacility, PDL, ValidIdType, UserProfile, VisitationAppointment } from '../types';

export const PHILIPPINE_MUNICIPALITIES = [
  'Imus City, Cavite',
  'Bacoor City, Cavite',
  'Dasmariñas City, Cavite',
  'General Trias City, Cavite',
  'Kawit, Cavite',
  'Noveleta, Cavite',
  'Cavite City, Cavite',
  'Rosario, Cavite',
  'Tanza, Cavite',
  'Trece Martires City, Cavite',
  'Silang, Cavite',
  'Tagaytay City, Cavite',
  'Manila City, Metro Manila',
  'Quezon City, Metro Manila',
  'Caloocan City, Metro Manila',
  'Pasig City, Metro Manila',
  'Taguig City, Metro Manila',
  'Parañaque City, Metro Manila',
  'Valenzuela City, Metro Manila',
  'Las Piñas City, Metro Manila',
  'Makati City, Metro Manila',
  'Muntinlupa City, Metro Manila',
  'Pasay City, Metro Manila',
  'Calamba City, Laguna',
  'Santa Rosa City, Laguna',
  'Biñan City, Laguna',
  'Batangas City, Batangas',
  'Antipolo City, Rizal',
  'Angeles City, Pampanga',
  'Cebu City, Cebu',
  'Davao City, Davao del Sur',
];

export const VALID_ID_OPTIONS: ValidIdType[] = [
  'Philippine National ID (PhilSys)',
  "Driver's License (LTO)",
  'Philippine Passport (DFA)',
  'UMID (Unified Multi-Purpose ID)',
  'Postal ID (Digitized)',
  'Social Security System (SSS) ID',
  "Voter's ID / Comelec Certification",
  'PRC Professional Identification Card',
  'Senior Citizen ID',
  'PhilHealth Identification Card',
];

export const BJMP_JAIL_FACILITIES: JailFacility[] = [
  {
    id: 'imus-city-jail-male',
    name: 'BJMP Imus City Jail - Male Dormitory',
    region: 'Region IV-A (CALABARZON)',
    municipality: 'Imus City, Cavite',
    address: 'Brgy. Malagasang 1-G, Imus City, Cavite 4103 (Near City Government Center)',
    contactNumber: '(046) 471-2854 / +63 917 839 2044',
    visitingDays: 'Tuesday to Sunday (Closed Mondays for Maintenance & Sanitation)',
    visitingHours: 'Morning: 8:00 AM - 11:30 AM | Afternoon: 1:00 PM - 4:00 PM',
    biometricDeskHours: 'Monday to Friday: 8:00 AM - 4:00 PM (Admin & Records Section, Gate 1)',
    capacityPerSlot: 40,
  },
  {
    id: 'imus-city-jail-female',
    name: 'BJMP Imus City Jail - Female Dormitory',
    region: 'Region IV-A (CALABARZON)',
    municipality: 'Imus City, Cavite',
    address: 'Brgy. Malagasang 1-G, Imus City, Cavite 4103',
    contactNumber: '(046) 471-2855 / +63 917 839 2045',
    visitingDays: 'Wednesday, Friday, Saturday, Sunday',
    visitingHours: 'Morning: 8:30 AM - 11:30 AM | Afternoon: 1:00 PM - 3:30 PM',
    biometricDeskHours: 'Monday to Friday: 8:00 AM - 4:00 PM (Female Dorm Records Unit)',
    capacityPerSlot: 30,
  },
  {
    id: 'dasmarinas-city-jail-male',
    name: 'BJMP Dasmariñas City Jail - Male Dormitory',
    region: 'Region IV-A (CALABARZON)',
    municipality: 'Dasmariñas City, Cavite',
    address: 'Brgy. Burol Main, Dasmariñas City, Cavite',
    contactNumber: '(046) 416-0922 / +63 918 200 4110',
    visitingDays: 'Tuesday, Thursday, Saturday, Sunday',
    visitingHours: 'Morning: 8:30 AM - 11:30 AM | Afternoon: 1:00 PM - 4:00 PM',
    biometricDeskHours: 'Monday to Friday: 8:00 AM - 4:00 PM',
    capacityPerSlot: 35,
  },
  {
    id: 'bacoor-city-jail-male',
    name: 'BJMP Bacoor City Jail - Male Dormitory',
    region: 'Region IV-A (CALABARZON)',
    municipality: 'Bacoor City, Cavite',
    address: 'Molino Boulevard, Brgy. Bayanan, Bacoor City, Cavite',
    contactNumber: '(046) 434-1188 / +63 919 443 1920',
    visitingDays: 'Wednesday to Sunday',
    visitingHours: '9:00 AM - 3:30 PM',
    biometricDeskHours: 'Monday to Friday: 8:00 AM - 4:00 PM',
    capacityPerSlot: 35,
  },
];

export const SAMPLE_PDL_ROSTER: PDL[] = [
  {
    id: 'pdl-001',
    pdlNumber: 'PDL-2024-00192',
    fullName: 'Juan Dela Cruz y Santos',
    jailFacilityId: 'imus-city-jail-male',
    cellDormitory: 'Brigada 3 - Cell Dorm B',
    status: 'In Custody',
    allowedVisitorRelationship: ['Spouse', 'Parent', 'Child', 'Sibling', 'Legal Counsel'],
  },
  {
    id: 'pdl-002',
    pdlNumber: 'PDL-2023-08411',
    fullName: 'Eduardo Martinez y Reyes',
    jailFacilityId: 'imus-city-jail-male',
    cellDormitory: 'Brigada 1 - Main Dormitory',
    status: 'In Custody',
    allowedVisitorRelationship: ['Spouse', 'Parent', 'Child', 'Sibling', 'Legal Counsel'],
  },
  {
    id: 'pdl-003',
    pdlNumber: 'PDL-2024-01588',
    fullName: 'Maria Teresa Mendoza y Garcia',
    jailFacilityId: 'imus-city-jail-female',
    cellDormitory: 'Female Brigada 1 - Dorm A',
    status: 'In Custody',
    allowedVisitorRelationship: ['Spouse', 'Parent', 'Child', 'Sibling', 'Legal Counsel'],
  },
  {
    id: 'pdl-004',
    pdlNumber: 'PDL-2024-03290',
    fullName: 'Antonio Ramos y Dimaguiba',
    jailFacilityId: 'imus-city-jail-male',
    cellDormitory: 'Building B - Sector 2',
    status: 'In Custody',
    allowedVisitorRelationship: ['Spouse', 'Parent', 'Child', 'Sibling', 'Legal Counsel', 'Friend/Relative'],
  },
  {
    id: 'pdl-005',
    pdlNumber: 'PDL-2024-04102',
    fullName: 'Michael Angelo Bautista y Cruz',
    jailFacilityId: 'imus-city-jail-male',
    cellDormitory: 'Security Dormitory 4',
    status: 'In Custody',
    allowedVisitorRelationship: ['Spouse', 'Parent', 'Child', 'Sibling', 'Legal Counsel'],
  },
  {
    id: 'pdl-006',
    pdlNumber: 'PDL-2024-05521',
    fullName: 'Jennifer Castillo y Alcantara',
    jailFacilityId: 'imus-city-jail-female',
    cellDormitory: 'Female Brigada 2 - Dorm B',
    status: 'In Custody',
    allowedVisitorRelationship: ['Spouse', 'Parent', 'Child', 'Sibling', 'Legal Counsel'],
  },
];

export const BJMP_RULES_AND_DRESS_CODE = {
  dressCodeProhibited: [
    { rule: 'NO Yellow or Orange Clothing', reason: 'Matches official PDL / inmate institutional uniform' },
    { rule: 'NO Camouflage or Military Attire', reason: 'Strictly reserved for uniformed military/law enforcement' },
    { rule: 'NO Sleeveless / Tank Tops / Crop Tops', reason: 'Indecent or revealing attire strictly prohibited' },
    { rule: 'NO Short Shorts or Mini Skirts', reason: 'Pants/skirts must fall below the knee' },
    { rule: 'NO Open-Toed Slippers / Flip-flops', reason: 'Closed shoes or strapped sandals required for facility safety' },
    { rule: 'NO Dark Sunglasses or Caps/Hats', reason: 'Full facial visibility required under CCTV cameras' },
  ],
  allowedPaabotItems: [
    'Cooked food in transparent/clear plastic tupperware or clear plastic bags (maximum 2 containers)',
    'Unopened bottled water or clear juice in sealed transparent PET bottles (no colored opaque flasks)',
    'Doctor-prescribed medicines with original medical prescription and label matching PDL name',
    'Plain white t-shirts, plain briefs/panties, and face towels without metal or strings',
    'Toiletries (soap bar, toothbrush, small toothpaste) without glass or metal containers',
  ],
  prohibitedContraband: [
    'Cellular phones, smartwatches, recording devices, or electronic gadgets',
    'Weapons, bladed items, scissors, nail clippers, or pointed objects',
    'Alcoholic beverages, cigarettes, vapes, or illegal substances',
    'Large sums of cash (exceeding allowance) or gambling paraphernalia',
    'Canned goods with metal pull-tabs, wire ropes, or metallic containers',
  ],
  biometricRequirements: [
    'Original copy of the valid government ID presented during online registration',
    'Official Printed or Digital Biometric Reference Slip with QR Code',
    'Two (2) pieces 2x2 recent ID pictures with white background',
    'Personal physical presence of the registrant at the BJMP Jail Biometrics Desk',
  ],
};

export const INITIAL_DEMO_USERS: UserProfile[] = [
  {
    id: 'user-activated-01',
    firstName: 'Maria Corazon',
    middleName: 'Alvarez',
    lastName: 'Santos',
    suffix: '',
    dateOfBirth: '1989-05-14',
    gender: 'Female',
    contactNumber: '+63 917 555 4321',
    email: 'maria.santos@gmail.com',
    password: 'password123',
    address: {
      houseUnitStreet: '#42 Aguinaldo Highway, Brgy. Malagasang 1-G',
      municipality: 'Imus City, Cavite',
      maritalStatus: 'Married',
      zipCode: '4103',
    },
    validIdType: 'Philippine National ID (PhilSys)',
    idPhotoUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=600&q=80',
    facePhotoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
    accountStatus: 'ACTIVATED',
    emailVerifiedAt: '2026-09-02 10:14:00',
    biometricReferenceNumber: 'BJMP-BIO-IMUS-9921',
    preferredJailFacilityId: 'imus-city-jail-male',
    biometricScannedAt: '2026-09-03 14:22:15',
    biometricsOfficerName: 'JO2 R. BAUTISTA (BJMP Imus Records Desk)',
    registeredAt: '2026-09-02 09:40:00',
  },
  {
    id: 'user-biometrics-pending-02',
    firstName: 'Roberto',
    middleName: 'Gomez',
    lastName: 'Reyes',
    suffix: 'Jr.',
    dateOfBirth: '1995-11-20',
    gender: 'Male',
    contactNumber: '+63 920 889 1234',
    email: 'roberto.reyes@yahoo.com',
    password: 'password123',
    address: {
      houseUnitStreet: 'Block 5 Lot 18, Bucandala Subd., Brgy. Bucandala III',
      municipality: 'Imus City, Cavite',
      maritalStatus: 'Single',
      zipCode: '4103',
    },
    validIdType: "Driver's License (LTO)",
    idPhotoUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80',
    facePhotoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    accountStatus: 'PENDING_BIOMETRICS',
    emailVerifiedAt: '2026-09-07 16:30:00',
    biometricReferenceNumber: 'BJMP-BIO-IMUS-7841',
    preferredJailFacilityId: 'imus-city-jail-male',
    registeredAt: '2026-09-07 16:15:00',
  },
  {
    id: 'user-email-pending-03',
    firstName: 'Elena',
    middleName: 'Soriano',
    lastName: 'Mercado',
    suffix: '',
    dateOfBirth: '1992-03-08',
    gender: 'Female',
    contactNumber: '+63 918 334 9901',
    email: 'elena.mercado@outlook.com',
    password: 'password123',
    address: {
      houseUnitStreet: 'Unit 304, Anabu Green Estates, Brgy. Anabu II-D',
      municipality: 'Imus City, Cavite',
      maritalStatus: 'Single',
      zipCode: '4103',
    },
    validIdType: 'UMID (Unified Multi-Purpose ID)',
    idPhotoUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=600&q=80',
    facePhotoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    accountStatus: 'PENDING_EMAIL',
    biometricReferenceNumber: 'BJMP-BIO-IMUS-4432',
    preferredJailFacilityId: 'imus-city-jail-female',
    registeredAt: '2026-09-08 00:30:00',
  },
];

export const INITIAL_APPOINTMENTS: VisitationAppointment[] = [
  {
    id: 'appt-101',
    appointmentReference: 'BJMP-VIS-IMUS-04421',
    userId: 'user-activated-01',
    visitorName: 'Maria Corazon Santos',
    visitorContact: '+63 917 555 4321',
    pdlId: 'pdl-001',
    pdlName: 'Juan Dela Cruz y Santos',
    pdlNumber: 'PDL-2024-00192',
    jailFacilityId: 'imus-city-jail-male',
    jailFacilityName: 'BJMP Imus City Jail - Male Dormitory',
    cellDormitory: 'Brigada 3 - Cell Dorm B',
    visitType: 'Contact Visit',
    relationshipToPDL: 'Spouse',
    visitDate: '2026-09-12',
    timeSlot: 'Morning Batch (08:00 AM - 11:30 AM)',
    paabotItemsDescription: '2 clear containers of cooked beef caldereta and steamed rice, 1 sealed 1L Wilkins water, 2 plain white t-shirts.',
    status: 'Approved',
    createdAt: '2026-09-04 11:20:00',
    qrToken: 'BJMP-GATE-04421-IMUS-CAVITE',
  },
];
