import React, { useState } from 'react';
import { X, User, Mail, Phone, Lock, Home, AlertCircle, ArrowRight } from 'lucide-react';
import { UserProfile, Gender, MaritalStatus } from '../../types';
import { PHILIPPINE_MUNICIPALITIES } from '../../data/bjmpData';

interface SignUpModalProps { isOpen:boolean; onClose:()=>void; onRegisterSuccess:(newUser:UserProfile)=>void; }
const normalizedPhone=(input:string)=>{const x=input.trim().replace(/[\s()-]/g,'');if(/^09\d{9}$/.test(x))return `+63${x.slice(1)}`;if(/^\+639\d{9}$/.test(x))return x;return null};
export const SignUpModal:React.FC<SignUpModalProps>=({isOpen,onClose,onRegisterSuccess})=>{
 const [firstName,setFirstName]=useState(''),[middleName,setMiddleName]=useState(''),[lastName,setLastName]=useState(''),[suffix,setSuffix]=useState(''),[dateOfBirth,setDateOfBirth]=useState(''),[gender,setGender]=useState<Gender>('Prefer not to say'),[email,setEmail]=useState(''),[mobileNumber,setMobileNumber]=useState(''),[password,setPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState(''),[street,setStreet]=useState(''),[municipality,setMunicipality]=useState(PHILIPPINE_MUNICIPALITIES[0]),[maritalStatus,setMaritalStatus]=useState<MaritalStatus>('Single'),[zipCode,setZipCode]=useState('4103'),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 if(!isOpen)return null;
 const phoneError=mobileNumber.length>0&&!normalizedPhone(mobileNumber);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(!firstName.trim()||!lastName.trim())return setError('Enter your first and last name.');if((!email.trim()&&!mobileNumber.trim())||(email.trim()&&mobileNumber.trim()))return setError('Choose exactly one: email address or Philippine mobile number.');if(email.trim()&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim()))return setError('Enter a valid email address.');if(mobileNumber.trim()&&!normalizedPhone(mobileNumber))return setError('Please enter a valid Philippine mobile number.');if(!dateOfBirth)return setError('Enter your date of birth.');if(!/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z0-9]).{8,128}$/.test(password))return setError('Password needs 8+ characters with uppercase, lowercase, number, and symbol.');if(password!==confirmPassword)return setError('Passwords do not match.');if(!street.trim()||!zipCode.trim())return setError('Enter your street address and ZIP code.');
  const user:UserProfile={id:'',firstName:firstName.trim(),middleName:middleName.trim(),lastName:lastName.trim(),suffix:suffix.trim(),dateOfBirth,gender,email:email.trim().toLowerCase(),mobileNumber:normalizedPhone(mobileNumber)||undefined,password,address:{houseUnitStreet:street.trim(),municipality,maritalStatus,zipCode:zipCode.trim()},accountStatus:'PENDING_VERIFICATION',biometricReferenceNumber:'',preferredJailFacilityId:'imus-city-jail-male',registeredAt:new Date().toISOString()};
  setSaving(true);try{await onRegisterSuccess(user)}finally{setSaving(false)}
 };
 const input='w-full rounded-xl border border-white/20 bg-slate-950/70 px-3.5 py-3 text-sm text-white placeholder:text-slate-500 outline-none focus:border-blue-400';
 return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-950/80 p-4 backdrop-blur-sm"><section className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-2xl border border-white/15 bg-slate-950 p-6 shadow-2xl sm:p-8">
  <header className="mb-6 flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-300">Visitor account</p><h2 className="mt-1 text-2xl font-bold text-white">Create your account</h2><p className="mt-1 text-sm text-slate-300">Verify one contact method, then submit your ID for administrator review.</p></div><button onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-white/10 hover:text-white" aria-label="Close"><X/></button></header>
  {error&&<div className="mb-4 flex gap-2 rounded-xl border border-rose-400/30 bg-rose-400/10 p-3 text-sm text-rose-200"><AlertCircle className="h-4 w-4 shrink-0"/>{error}</div>}
  <form onSubmit={submit} className="space-y-5"><div><h3 className="mb-3 text-sm font-semibold text-white">Personal information</h3><div className="grid gap-3 sm:grid-cols-2"><input className={input} placeholder="First name" value={firstName} onChange={e=>setFirstName(e.target.value)} required/><input className={input} placeholder="Middle name (optional)" value={middleName} onChange={e=>setMiddleName(e.target.value)}/><input className={input} placeholder="Last name" value={lastName} onChange={e=>setLastName(e.target.value)} required/><input className={input} placeholder="Suffix (optional)" value={suffix} onChange={e=>setSuffix(e.target.value)}/><label className="text-xs text-slate-300">Date of birth<input type="date" className={`${input} mt-1`} value={dateOfBirth} onChange={e=>setDateOfBirth(e.target.value)} required/></label><select className={input} value={gender} onChange={e=>setGender(e.target.value as Gender)}><option>Prefer not to say</option><option>Female</option><option>Male</option><option>Other</option></select></div></div>
  <div><h3 className="mb-1 text-sm font-semibold text-white">Choose a sign-in contact</h3><p className="mb-3 text-xs text-slate-400">Enter either an email address or a Philippine mobile number.</p><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-slate-300"><Mail className="mr-1 inline h-3.5 w-3.5"/>Email<input className={`${input} mt-1`} type="email" autoComplete="email" placeholder="name@example.com" value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="text-xs text-slate-300"><Phone className="mr-1 inline h-3.5 w-3.5"/>Philippine mobile number<input className={`${input} mt-1 ${phoneError?'border-rose-400':''}`} type="tel" autoComplete="tel" placeholder="09171234567 or +639171234567" value={mobileNumber} onChange={e=>setMobileNumber(e.target.value)}/>{phoneError&&<span className="mt-1 block text-rose-300">Please enter a valid Philippine mobile number.</span>}</label></div></div>
  <div><h3 className="mb-3 text-sm font-semibold text-white">Password</h3><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-slate-300"><Lock className="mr-1 inline h-3.5 w-3.5"/>Password<input className={`${input} mt-1`} type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={8}/></label><label className="text-xs text-slate-300">Confirm password<input className={`${input} mt-1`} type="password" autoComplete="new-password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} required/></label></div></div>
  <div><h3 className="mb-3 text-sm font-semibold text-white"><Home className="mr-1 inline h-4 w-4"/>Address</h3><div className="grid gap-3 sm:grid-cols-2"><input className={input} placeholder="House / unit / street" value={street} onChange={e=>setStreet(e.target.value)} required/><select className={input} value={municipality} onChange={e=>setMunicipality(e.target.value)}>{PHILIPPINE_MUNICIPALITIES.map(x=><option key={x}>{x}</option>)}</select><select className={input} value={maritalStatus} onChange={e=>setMaritalStatus(e.target.value as MaritalStatus)}>{['Single','Married','Widowed','Separated','Divorced'].map(x=><option key={x}>{x}</option>)}</select><input className={input} placeholder="ZIP code" value={zipCode} onChange={e=>setZipCode(e.target.value)} required/></div></div>
  <div className="rounded-xl border border-blue-400/20 bg-blue-400/5 p-3 text-xs leading-relaxed text-slate-300">After contact verification, upload your ID through the protected Identity Verification page. Uploaded documents are kept private and must be reviewed by an administrator.</div>
  <footer className="flex justify-end border-t border-white/10 pt-4"><button disabled={saving||phoneError} className="flex items-center gap-2 rounded-xl bg-blue-500 px-5 py-3 text-sm font-bold text-slate-950 disabled:opacity-50">{saving?'Creating account…':<>Create account <ArrowRight className="h-4 w-4"/></>}</button></footer></form>
 </section></div>
};
